### PR TITLE
Modularizing tanzu deps

### PR DESCRIPTION
**Pull request by jmarhee**

### CODE REVIEW

**Comment by jmarhee** [comment]
Largely a note to self, but for documentary reasons: This will be published as a module, so running the module should yield a completed installation of the software, even if it does require invoking multiple submodules piecemeal due to the manual nature of some of the components (i.e. some of these steps require connecting to the provisioned VPN before proceeding, otherwise require configuration that Terraform providers for certain components do not yet handle)-- `main.tf` should reflect this to some degree, so maybe these submodules can be condensed and, itself, invoke the vsphere module, rather than in the root module, and the substance of this module becoming secondary.

**Comment by jmarhee** [comment]
Updating to include the submodules and imported module to main.tf-- the README will, instead, reflect the order of application from the root module since the examples are not ideal for a registry-imported pull.

**Comment by jmarhee** [comment]
- [ ] `outputs.tf` needs updating

- [ ] `variables.tf` needs descriptions and defaults

**Comment by jmarhee** [comment]
Updating on this: since I moved most of everything into submodules (or import the dependent module, if we've a registry entry for it), I'm mostly shaking out variables and outputs still-- a lot of those currently in the branch are supporting variables for the other components, and have been moved to the relevant submodule or example that demonstrates an instantiation. Once this is clean, I'll likely have this ready for review in the next push.

**Comment by displague** [comment]
@jmarhee I added the Terraform validation GH Action runner to this PR, the same used used in the vsphere module.

https://github.com/packet-labs/terraform-metal-tanzu/runs/2154132288?check_suite_focus=true

It is currently failing because there is an expectation for the user to copy the example/ snippets into the root.
To make this tanzu module reusable, that should not be the case. The module should be ready to go.  Any configuration parameters that the user would consider when copying files in from examples/ should be made into variables that this module exposes.

The examples/ directory can be repurposed for configurations that showcase usage of "equinix/tanzu/metal" (rather than "equinix/vsphere/metal").  The examples show how to use this module, not how to prepare this module.

I'll add another commit and prepare the integration environment variables here so that we can have those tests running for this PR.

I've been whittling away at the problems and requirements for vsphere integration testing in https://github.com/equinix/terraform-metal-vsphere/pull/16 (and earlier PRs).

**Comment by displague** [comment]
Similar changes were made to the openstack module: 
https://github.com/equinix/terraform-metal-openstack/tree/master/examples

Integration tests on that repo are succeeding.

**Comment by displague** [comment]
@jmarhee I've pushed up several commits to make the changes I described above.

I'm not sure what value should be supplied to the `nsxt` provider, but I assume it is something coming from the module.vsphere module.

I haven't looked at the README.md - I'm sure we will need to update it to not rely on copying data from the examples.

The validation test is now passing.
The integration test will not pass until we have configured the correct secrets for this project.  I expect we will want to hold off on that until the vsphere integration test is passing. equinix/terraform-metal-vsphere#15

**Comment by displague** [comment]
We'll also want to add descriptions to all variables and outputs. We can copy many of these descriptions from the vsphere module.

We can also set the variables types.
Sensitive variables should take advantage of the property that identifies them as such.

**Comment by jmarhee** [comment]
I was working on a lot of these issues already (why this was a draft), and didn’t receive any notifications for this work in your above commits for some reason, so I’ll now need to go back an reconcile all of my un-pushed work because there’s a number of conflicts now in my local branch. I’ll update again shortly once I finish that and hopefully address your outstanding concerns above. Thanks.

**Pull request merged**
